#ifndef MAINTENANCE_CONFIG_H
#define MAINTENANCE_CONFIG_H

/* All application-specific settings are collected here. */
#define MAINTENANCE_DEFAULT_DAYS       180U
#define MAINTENANCE_SENSOR_DEFAULT_DAYS 180U
#define MAINTENANCE_MAX_DAYS           36500U
#define MAINTENANCE_DEFAULT_HOURS      8000U
#define MAINTENANCE_SENSOR_DEFAULT_HOURS 8000U
#define MAINTENANCE_SAVE_INTERVAL_SECONDS 60U
#define MAINTENANCE_SCREEN_BOOT_MS     2000U
#define MAINTENANCE_RTC_POLL_MS        1000U
#define MAINTENANCE_RTC_TIMEOUT_MS     500U
#define MAINTENANCE_RTC_FRESH_MS       3000U
#define MAINTENANCE_STORAGE_RETRY_MS   5000U
#define MAINTENANCE_FRAME_TIMEOUT_MS   200U
#define MAINTENANCE_DISPLAY_PERIOD_MS 1000U

/* 24C256: A0/A1/A2 are grounded. Reserve a 32-page cyclic journal.
 * Do not allocate these addresses to other application settings. */
#define MAINTENANCE_EEPROM_ADDRESS     0x50U
#define MAINTENANCE_EEPROM_SLOT0       0x7F00U
#define MAINTENANCE_EEPROM_SLOT1       0x7F40U
#define MAINTENANCE_EEPROM_PAGE_SIZE   64U
#define MAINTENANCE_EEPROM_JOURNAL_BASE 0x7800U
#define MAINTENANCE_EEPROM_SLOT_COUNT  32U

/* Screen0, display only. All maintenance logic runs on the MCU.
 * 0xFFFF disables an output. Dacai protocol, CRC disabled, 115200 8N1.
 * RTC control 10 displays the same system RTC read by command EE 82. */
#ifndef MAINTENANCE_SCREEN_ID
#define MAINTENANCE_SCREEN_ID 0U
#endif
#define MAINTENANCE_MACHINE_PERIOD_ID   1U
#define MAINTENANCE_MACHINE_PROGRESS_ID 2U
#define MAINTENANCE_SENSOR_PROGRESS_ID  3U
#define MAINTENANCE_SENSOR_PERIOD_ID    4U
#define MAINTENANCE_MACHINE_BAR_ID      5U
#define MAINTENANCE_SENSOR_BAR_ID       6U
#define MAINTENANCE_RTC_CONTROL_ID     10U
#define MAINTENANCE_MACHINE_HOURS_ID   17U
#define MAINTENANCE_SENSOR_HOURS_ID    18U
#define MAINTENANCE_MACHINE_STATUS_ID  19U
#define MAINTENANCE_SENSOR_STATUS_ID   20U
#define MAINTENANCE_COLOR_NORMAL       0x2359U /* RGB565: 36,105,201 */
#define MAINTENANCE_COLOR_DUE          0xC9E9U /* RGB565: 200,63,73 */

#define MAINTENANCE_RX_SIZE            512U
#define MAINTENANCE_FRAME_SIZE         1024U
#define MAINTENANCE_TX_SIZE            64U

#endif
